Feature/profiles UI components v2
relaycc/relay pull request #123
Opened 2022-08-04 20:19 UTC by BrianS111

## Issue link

_link to github issue_

## Description

_description of proposed changes_

## Additional Information

2022-08-04 20:21 UTC, BrianS111 commented
https://www.notion.so/daopanel/629a20e30c6548c0adbbd152ab54fe7f?v=5a9ec17bb04d4cc7b69b429da2322a27&p=aa9d20c1acbc4569861ec571135727e7&pm=c

This is the PR for the updated figma designs

2022-08-05 23:37 UTC, killthebuddh4 commented on src/elements/cards/index.ts
> +export * from '../cards';
Each index file should export the other files that share its directory. The examples in the ticket show how to do this.

2022-08-05 23:44 UTC, killthebuddh4 reviewed
* The `TestingSupplies` directory should be removed. If any of the components are importing files from it, those files should be move to `/public`.
* A couple minor notes that I don't expect to be changed right now but wanted to highlight
  - I think these components use more HTML elements and/or styled components than necessary. Many times wrappers/containers aren't absolutely necessary.
  - Passing props to styled components I think is something that should only be done rarely when there's no other way to do what you want to accomplish.

2022-08-05 23:44 UTC, killthebuddh4 commented on src/elements/cards/index.ts
> +export * from '../cards';
Each index file should export the other files that share its directory. The examples in the ticket show how to do this.

2022-08-05 23:44 UTC, killthebuddh4 commented on src/elements/externalProfiles/index.ts
> +export * from '../externalProfiles';
Each index file should export the other files that share its directory. The examples in the ticket show how to do this.

2022-08-08 17:15 UTC, BrianS111 commented
1. I removed the testing supplies directory. 

2. RE:  I don't see any event handlers anywhere. I think some of these components should definitely take at least a click handler. This might be something to ask UI/UX team about. 

The reason there are no event handlers is because there is what appears to be a link to open the NFT or DAO directory in a separate window, and that seems to be the only functionality one would want from those components. Maybe I can ask design what is going to happen when it is clicked? Maybe some separate modal opens up? But I didn't see designs for anything of the sort. 

Maybe I can put an event handler on the Verify now button? But I wasnt sure what that was. The user clicks the button and then it switches to verified? I thought it might be a badge getting data from backend and it either shows the user is verified or not. Again, more questions for design I guess.

Minor notes
1. No, they are all serving a purpose to fulfill edge cases and make the layout perfect from any view
2. passing props to styled components is only a performance issue if it's a prop that changes to a bunch of different things (objects moving aroudn the screen) and styled components has to generate a new class name for each one. For booleans and such, it isn't an issue. If there is a different format you want me to follow for 'code structure' purposes I can do that also

2022-08-08 17:24 UTC, killthebuddh4 commented
@BrianS111 Please add the following click handlers

* The NFT and DAO cards should have `onClickImage` handlers. 
* The `externalProfiles` cards should have `onClickCard`
* The `externalProfiles` card with the "Verify Now" button should also have a `onClickButton` handler
* Each of the click handlers I think should have the type signature `() => unknown`

Also please update the index files according to the comments above.

2022-08-08 18:28 UTC, killthebuddh4 requested changes

2022-08-08 18:28 UTC, killthebuddh4 commented on src/elements/cards/DAOCard.tsx
> +          style={{ cursor: onClickImage == null ? 'default' : 'pointer' }}>
It's good practice to avoid the `==` operator whenever possible (basically 100% of the time). Use `===` instead. Please update this line and I think there's one or two other places in this PR where it's being used. I'm actually surprised this isn't making our linter throw an error, I'll need to look into it.

2022-08-12 19:11 UTC, killthebuddh4 commented
Closing because this is duped by the bigger UI components PR.

2022-08-12 19:11 UTC, closed without merging