Feature/additional components
relaycc/relay pull request #125
Opened 2022-08-11 18:55 UTC by BrianS111

https://www.notion.so/relaycc/629a20e30c6548c0adbbd152ab54fe7f?v=5a9ec17bb04d4cc7b69b429da2322a27&p=aa9d20c1acbc4569861ec571135727e7&pm=c

2022-08-12 19:11 UTC, killthebuddh4 requested changes
A couple comments I repeated a bunch of places so I'll just do a top-level comment:
* Any interface for an exported function should also be exported
* component interfaces should be named the same as the component but with "Props" appended: `MyComponent` should have interface `MyComponentProps`
* All `.png` files should be moved to `public`.

Most of the comments I left are about naming and exporting. I might have missed some of the cases where naming/exporting could be updated, it might be worthwhile to do a once-over and fix any cases where I missed.

2022-08-12 19:11 UTC, killthebuddh4 commented on src/elements/ChatHeader/ChatHeaderLightWithToggle.tsx
> +interface Props {
I'm just going to leave a top-level comment about interface exports.

2022-08-12 19:11 UTC, killthebuddh4 commented on src/elements/switchPrimary/switchPrimary.tsx
> +export const switchPrimary = ({ textContent, isPrimary, onClick }: Props) => {
This should be `PascalCase` (the directory should be too).

2022-08-12 19:11 UTC, killthebuddh4 commented on src/elements/textBox/TextArea.tsx
> +export const TextArea = () => {
This component should have some basic/default event handlers.

2022-08-12 19:11 UTC, killthebuddh4 commented on src/elements/textBox/TextInput.tsx
> +export const TextInput = () => {
This should have some basic event handlers.

2022-08-12 19:12 UTC, killthebuddh4 commented
Oh last thing to note is the failing linter check. Commenting so it can be "resolved" like a comment.

2022-08-15 22:30 UTC, killthebuddh4 commented on src/elements/switchPrimary/switchPrimary.tsx
> +export const switchPrimary = ({ textContent, isPrimary, onClick }: Props) => {
@BrianS111 I think this one got missed.

2022-08-15 22:33 UTC, killthebuddh4 commented
>     * Any interface for an exported function should also be exported

This one got missed. The interfaces for each React component should be exported.

>     * All `.png` files should be moved to `public`.

This one got missed.

2022-08-15 22:40 UTC, killthebuddh4 requested changes

2022-08-15 22:40 UTC, killthebuddh4 commented on src/elements/Buttons/SecondaryButton.tsx
> +interface SecondaryButtonProps {
This should be exported.

2022-08-15 22:40 UTC, killthebuddh4 commented on src/elements/ChatComponent/ChatComponent.tsx
> +interface ChatComponentProps {
This should be exported.

2022-08-15 22:40 UTC, killthebuddh4 commented on src/elements/cards/DAOCard.tsx
> +interface DAOCardProps {
This should be exported.

2022-08-15 22:40 UTC, killthebuddh4 commented on src/elements/cards/NFTCard.tsx
> +interface NFTCardProps {
This should be exported.

2022-08-15 22:40 UTC, killthebuddh4 commented on src/elements/switchPrimary/switchPrimary.tsx
> +export const switchPrimary = ({
`PascalCase` here. Filename should be updated  too.

2022-08-15 22:40 UTC, killthebuddh4 commented on src/elements/textBox/TextArea.tsx
> +export interface TextAreaProps {
You don't need to update this right now, but it might help to think about how the user input is going to make it from this component to it's parent component. The callbacks are going to need to take some arguments I think.

2022-08-15 22:42 UTC, killthebuddh4 commented on src/elements/ChatHeader/index.ts
> +export * from './ChatHeaderAll';
`ChatHeaderAll` shouldn't be exported.

2022-08-15 22:43 UTC, killthebuddh4 commented on src/elements/ChatHeader/ChatHeaderAll.tsx
> +import styled from 'styled-components';
@BrianS111 make sure `ChatHeaderAll` isn't exported.

2022-08-15 22:44 UTC, killthebuddh4 commented on src/elements/ChatHeader/ChatHeaderDarkExitOnly.tsx
> +interface Props {
@BrianS111 This one got missed.

2022-08-16 16:49 UTC, killthebuddh4 commented on src/elements/ChatHeader/ChatHeaderDarkExitOnly.tsx
> +interface Props {
@BrianS111 This one still.

2022-08-16 19:47 UTC, BrianS111 commented on src/elements/ChatHeader/ChatHeaderDarkExitOnly.tsx
> +interface Props {
Fixed

2022-08-16 19:48 UTC, BrianS111 commented on src/elements/switchPrimary/switchPrimary.tsx
> +export const switchPrimary = ({ textContent, isPrimary, onClick }: Props) => {
Got it. All component files are now in Pascal case

2022-08-16 20:03 UTC, BrianS111 commented on src/elements/switchPrimary/switchPrimary.tsx
> +export const switchPrimary = ({
Done.

2022-08-16 20:27 UTC, killthebuddh4 approved these changes

2022-08-16 20:40 UTC, merged