Truncated names now show the first 15 characters
relaycc/relay pull request #127
Opened 2022-08-15 22:50 UTC by BrianS111

2022-08-15 23:07 UTC, killthebuddh4 requested changes

2022-08-15 23:07 UTC, killthebuddh4 commented on src/hooks/useResponsiveUserId.ts
> +    return str.slice(0, 15) + '...' + str.slice(-3);
Is there a way to do this so that the "truncated" version of the name is never longer than the name itself? As is, for example, `ThisIsACoolName.eth` would get "truncated" to `ThisIsACoolName...eth`

2022-08-16 19:25 UTC, BrianS111 commented on src/hooks/useResponsiveUserId.ts
> +    return str.slice(0, 15) + '...' + str.slice(-3);
Yes. fixed so that no names get longer after truncating regardless of length

2022-08-17 22:28 UTC, killthebuddh4 approved these changes

2022-08-18 21:09 UTC, merged