adding polygon card
relaycc/relay pull request #46
Opened 2022-10-20 21:42 UTC by BrianS111

draft PR for https://github.com/relaycc/relay/issues/41

2022-10-20 22:04 UTC, BrianS111 commented
https://user-images.githubusercontent.com/81312527/197067701-1c71c30f-09cb-4be8-899f-8e760a3b1685.mov

This PR is ready to be merged

2022-10-20 23:38 UTC, killthebuddh4 requested changes

2022-10-20 23:38 UTC, killthebuddh4 commented on src/components/pages/Profile.tsx
> +            logoAlt="Polydon Id Logo"
Typo.

2022-10-20 23:38 UTC, killthebuddh4 commented on src/components/pages/Profile.tsx
> +        fadeOut={<LogoCard title="PolygonId" logo={"/polygonid.svg"} />}
The display string for this should have a space between "polygon" and "id". See 
<img width="829" alt="image" src="https://user-images.githubusercontent.com/100799178/197078835-e3fb207d-3537-48a9-8a0f-0bc669ea8195.png">

2022-10-21 17:15 UTC, BrianS111 commented
https://user-images.githubusercontent.com/81312527/197252231-9a7a9501-8d47-4a3f-9bf1-20a561735001.mov

This issue should now be complete

2022-10-21 18:14 UTC, BrianS111 commented
Typo is fixed. This should be ready to be merged

2022-10-21 18:15 UTC, killthebuddh4 approved these changes

2022-10-21 18:16 UTC, merged